name: Publish Contracts SDK

on:
  push:
    tags:
      - "publish-*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install Yarn
        run: npm install -g yarn@4.3.1

      - name: Install dependencies
        run: yarn install

      - name: Bump contracts-sdk version
        run: npx lerna version patch --no-push --yes --force-publish=contracts-sdk

      - name: Publish contracts-sdk package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx lerna publish from-package --yes --scope contracts-sdk

      - name: Bump contracts-build version
        run: npx lerna version patch --no-push --yes --force-publish=contracts-build

      - name: Publish contract-build package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx lerna publish from-package --yes --scope contracts-build

      - name: Push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git push origin main --follow-tags
